---
abstract: 'Dist::Zilla configuration the way CHIM does it'
author:
  - 'Anton Gerasimov <chim@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-Author-CHIM
no_index:
  directory:
    - t
    - xt
    - eg
    - examples
    - corpus
  namespace:
    - t::lib
  package:
    - DB
provides:
  Dist::Zilla::PluginBundle::Author::CHIM:
    file: lib/Dist/Zilla/PluginBundle/Author/CHIM.pm
    version: 0.01
requires:
  Dist::Zilla: 4.300030
  Dist::Zilla::Plugin::Authority: 1.006
  Dist::Zilla::Plugin::MetaProvides::Package: 1.14000001
  Dist::Zilla::Plugin::OurPkgVersion: 0.004000
  Dist::Zilla::Plugin::PodWeaver: 3.101641
  Dist::Zilla::Plugin::ReadmeAnyFromPod: 0.120120
  Dist::Zilla::Plugin::ReadmeFromPod: 0.18
  Dist::Zilla::Plugin::Test::Compile: 2.001
  Dist::Zilla::Plugin::Test::Kwalitee: 2.03
  Dist::Zilla::Plugin::Test::Version: 0.002004
resources:
  bugtracker: https://github.com/Wu-Wu/Dist-Zilla-PluginBundle-Author-CHIM/issues
  homepage: https://metacpan.org/release/Dist-Zilla-PluginBundle-Author-CHIM
  repository: git://github.com/Wu-Wu/Dist-Zilla-PluginBundle-Author-CHIM.git
version: 0.01
x_authority: cpan:CHIM
